import { useEffect, useState } from "react";
import { AttackTree } from "../components/AttackTree";
import { DiffViewer } from "../components/DiffViewer";
import { Metrics } from "../components/Metrics";
import { RepositoryExplorer } from "../components/RepositoryExplorer";
import { SandboxRun } from "../components/SandboxRun";
import { TestPlan } from "../components/TestPlan";
import { RunEvent, TerminalStream } from "../components/TerminalStream";
const API = "http://localhost:8000";
type Session = { id: string; status: string; events: RunEvent[]; incident?: { patch_diff?: string }; report?: any };
type Analysis = { repository_path: string; files_scanned: number; routes: any[]; execution_status: string; execution_note: string };
type ExecutionResult = { status: string; test_name: string; http_status?: number; logs: string; sandbox_policy: string };
export default function Home() {
  const [session, setSession] = useState<Session>(); const [busy, setBusy] = useState(false); const [approved, setApproved] = useState(false); const [executionAuthorized, setExecutionAuthorized] = useState(false); const [error, setError] = useState(""); const [repositoryPath, setRepositoryPath] = useState("mock-targets/vulnerable-node-app"); const [analysis, setAnalysis] = useState<Analysis>(); const [mapping, setMapping] = useState(false); const [execution, setExecution] = useState<ExecutionResult>(); const [runningValidation, setRunningValidation] = useState(false); const [archive, setArchive] = useState<File>(); const [uploading, setUploading] = useState(false);
  useEffect(() => {
    fetch(`${API}/sessions/latest`).then(async (response) => {
      if (!response.ok) return;
      const restored = await response.json() as Session;
      setSession(restored);
      if (!['resolved', 'failed'].includes(restored.status)) setBusy(true);
    }).catch(() => undefined);
    fetch(`${API}/repositories/latest`).then(async (response) => {
      if (!response.ok) return;
      const uploaded = await response.json() as { repository_path: string };
      setRepositoryPath(uploaded.repository_path);
    }).catch(() => undefined);
  }, []);
  const systemEvents: RunEvent[] = [...(session?.events?.map((event) => ({ ...event, message: `orchestrator • ${event.message}` })) ?? []), ...(session?.report?.sandbox_logs ? [{ timestamp: new Date().toISOString(), status: "container", message: session.report.sandbox_logs }] : [])];
  async function mapRepository(path = repositoryPath) { if (!approved) { setError("Confirm repository authorization before mapping source files."); return; } setMapping(true); setError(""); const response = await fetch(`${API}/repositories/analyze`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ repository_path: path, authorization_confirmed: true }) }); const body = await response.json(); if (!response.ok) { setError(body.detail ?? "Repository mapping failed."); setMapping(false); return; } setAnalysis(body); setMapping(false); }
  async function uploadRepository() { if (!archive) { setError("Choose a repository ZIP file first."); return; } if (!approved) { setError("Confirm repository authorization before uploading source files."); return; } setUploading(true); setError(""); const form = new FormData(); form.append("archive", archive); form.append("authorization_confirmed", "true"); const response = await fetch(`${API}/repositories/upload`, { method: "POST", body: form }); const body = await response.json(); if (!response.ok) { setError(body.detail ?? "Repository upload failed."); setUploading(false); return; } await fetch(`${API}/sessions/reset`, { method: "POST" }); setSession(undefined); setExecution(undefined); setAnalysis(undefined); setRepositoryPath(body.repository_path); setUploading(false); await mapRepository(body.repository_path); }
  async function start() { if (!approved || !executionAuthorized) { setError("Confirm repository and Docker execution authorization before starting the pipeline."); return; } setError(""); setBusy(true); const response = await fetch(`${API}/sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ target_path: repositoryPath, execution_authorized: true, model_authorized: true }) }); if (!response.ok) { const body = await response.json(); setError(body.detail ?? "The local API did not accept the pipeline request."); setBusy(false); return; } const created = await response.json(); setSession(created); const stream = new EventSource(`${API}/sessions/${created.id}/events`); stream.onmessage = (event) => { const updated = JSON.parse(event.data) as Session; setSession(updated); if (["resolved", "failed"].includes(updated.status)) { stream.close(); setBusy(false); } }; stream.onerror = () => { stream.close(); setBusy(false); setError("The local event stream disconnected."); }; }
  async function runValidation() { await start(); }
  return <main><header className="hero"><div><p className="eyebrow">LOCAL-ONLY RELIABILITY LAB</p><h1>HydraBench</h1><p>Multi-agent reliability testing for explicitly authorized targets.</p></div><div className="hero__state"><span className="pulse" /> API <b>CONNECTED</b><small>isolated execution enabled</small></div></header><section className="control-panel"><div><p className="kicker">REPOSITORY CONFIGURATION</p><h2>Upload or choose a workspace repository</h2><input className="upload-input" type="file" accept=".zip,application/zip" onChange={(event) => setArchive(event.target.files?.[0])} /><input className="repository-input" value={repositoryPath} onChange={(event) => setRepositoryPath(event.target.value)} aria-label="Repository path" /></div><div className="control-panel__actions"><label><input type="checkbox" checked={approved} onChange={(event) => setApproved(event.target.checked)} /> I own or am authorized to test this repository. Upload and mapping stay local; model sharing requires a separate run authorization.</label><button disabled={uploading} onClick={uploadRepository}>{uploading ? "Staging repository" : "Upload & map ZIP"}</button><button className="button-secondary" disabled={mapping} onClick={() => mapRepository()}>{mapping ? "Mapping repository" : "Map workspace path"}</button><button className="button-secondary" disabled={busy} onClick={start}>{busy ? "Agent run in progress" : "Start full agent + Docker run"}</button></div>{error && <p className="notice">{error}</p>}</section><Metrics session={session} /><RepositoryExplorer analysis={analysis} /><TestPlan plan={session?.report?.agent_test_plan} /><section className="execution-control"><label><input type="checkbox" checked={executionAuthorized} onChange={(event) => setExecutionAuthorized(event.target.checked)} /> I authorize bounded Docker validation for this uploaded Node repository. The container has no outbound network and is removed after testing.</label><button disabled={busy} onClick={runValidation}>{busy ? "Agent run in progress" : "Run full agent + Docker validation"}</button></section><SandboxRun result={execution} /><AttackTree status={session?.status ?? "queued"} /><div className="grid"><TerminalStream title="Agent output" events={session?.events ?? []} /><TerminalStream title="System events" events={systemEvents} tone="system" /><DiffViewer status={session?.status ?? "queued"} diff={session?.incident?.patch_diff} /></div></main>;
}
